# Generated by Django 5.2 on 2026-02-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_lead_installation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, choices=[('summer_sale', 'Summer Sale'), ('referral_program', 'Referral Program'), ('social_media_ad', 'Social Media Ad'), ('offline_event', 'Offline Event')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='medium',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('social_media', 'Social Media'), ('referral', 'Referral')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('chat', 'Chat'), ('website', 'Website'), ('walkin', 'Walk-in')], max_length=50, null=True),
        ),
    ]
