# Generated by Django 5.2 on 2026-02-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_alter_lead_campaign_alter_lead_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='average_monthly_bill',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='financing_preference',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='roof_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sanctioned_load',
        ),
        migrations.AlterField(
            model_name='lead',
            name='installation_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('offgrid', 'Off Grid')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('site_survey_scheduled', 'Site Survey Scheduled'), ('site_survey_done', 'Site Survey Done'), ('proposal_sent', 'Proposal/Quotation Sent'), ('negotiation', 'Negotiation'), ('order_confirmed', 'Order Confirmed'), ('installation_scheduled', 'Installation Scheduled'), ('installation_completed', 'Installation Completed')], default='new', max_length=50),
        ),
    ]
