# Generated by Django 5.2 on 2026-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_remove_lead_average_monthly_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='average_monthly_bill',
            field=models.IntegerField(blank=True, help_text='Enter electricity bill in ₹', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='financing_preference',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('loan', 'Loan'), ('emi', 'EMI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='roof_type',
            field=models.CharField(blank=True, choices=[('rcc', 'RCC'), ('sheet', 'Sheet'), ('tile', 'Tile'), ('metal', 'Metal'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sanctioned_load',
            field=models.FloatField(blank=True, help_text='Enter load in kW', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('site_survey_scheduled', 'Site Survey Scheduled'), ('site_survey_done', 'Site Survey Done'), ('proposal_sent', 'Proposal/Quotation Sent'), ('negotiation', 'Negotiation'), ('order_confirmed', 'Order Confirmed'), ('installation_scheduled', 'Installation Scheduled'), ('installation_completed', 'Installation Completed'), ('converted', 'Converted')], default='new', max_length=50),
        ),
    ]
