# Generated by Django 5.2 on 2026-03-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick'), ('casual', 'Casual'), ('paid', 'Paid')], max_length=20),
        ),
    ]
